//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parcial.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venta
    {
        public int VentaID { get; set; }
        public int ClienteID { get; set; }
        public int ViviendaID { get; set; }
        public System.DateTime FechaVenta { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Vivienda Vivienda { get; set; }
    }
}
