//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parcial.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vivienda
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vivienda()
        {
            this.Ventas = new HashSet<Venta>();
        }
    
        public int ViviendaID { get; set; }
        public int TipoViviendaID { get; set; }
        public int AgenciaID { get; set; }
        public int NumCuartos { get; set; }
        public int NumBanos { get; set; }
        public decimal TamanoMetrosCuadrados { get; set; }
        public int NumPisos { get; set; }
        public string Accesorios { get; set; }
    
        public virtual Agencia Agencia { get; set; }
        public virtual TipoVivienda TipoVivienda { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Venta> Ventas { get; set; }
    }
}
